site_name: Kamilla Vinokurova | TW

theme:
  name: material
  language: ru
  palette:
    primary: indigo

  icon:
    logo: material/file-document-edit



nav:
  - Обо мне | About: index.md

  - Портфолио | Portfolio:
      - Руководства пользователя | User Guides: portfolio/user-guides.md
      - Datasheets и паспорта | Datasheets & Specifications: portfolio/product-docs.md
      - Сертификация | Certificarion: portfolio/certification.md
      - Статьи и схемы | Articles & Diagrams: portfolio/articles-diagrams.md
      # - Подход и процессы: portfolio/processes.md

  - Контакты | Contacts: contacts.md

extra_css:
  - stylesheets/extra.css

